# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: 'Weecology'
    description: "Weecology's Lab Wiki"
    twitter: 'weecology'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: 'Â© 2022 The contributors. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: false
      allow_commercial: true

# Localization

locale:
  date_format: '2006-01-02'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/weecology/lab-manual'
    content_dir: content
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
